### ISSUE TITLE
Callback function may be doing redundant processing

### ISSUE THREAD

**Issue by antonywinn** [livehouse-automation/veraflux#13]
veraFluxWatchedVariableCallback(lul_device, lul_service, lul_variable, lul_value_old, lul_value_new) Callback function in L_VeraFlux1.lua is cycling through devices and verifying services are supported and listed in the services table. 

This processing may be redundant, as this check is done during callback setup veraFluxSetupCallbacks() - the only calls to veraFluxWatchedVariableCallback() would be valid ones setup during the initialisation.

Callback function could probably just take the parameters passed, add the tags and send direct to influx without rechecking all of the services and variables allowing it to complete more quickly and with fewer cpu cycles.

**Comment by mikenye** [comment]
Hopefully fixed in dev branch. Please test (@antonywinn).

**Comment by mikenye** [comment]
Fixed, and committed to master branch.
