### ISSUE TITLE
InfluxDB replying - connction refused

### ISSUE THREAD

**Issue by Mhaluch** [livehouse-automation/veraflux#14]
Hi,

I have implemented all the steps according to the guide and infludb replying that connection is refused, expected 204?

luup_log:483: VeraFlux #483 DEBUG veraFluxWatchedVariableCallback called: lul_device='232', lul_service='urn:micasaverde-com:serviceId:SecuritySensor1', lul_variable='Tripped', lul_value_old='0', lul_value_new='0 <0x743fa520>
50      03/17/19 16:12:46.141   luup_log:483: VeraFlux #483 DEBUG sendVeraFluxData called via veraFluxWatchedVariableCallback <0x743fa520>
50      03/17/19 16:12:46.141   luup_log:483: VeraFlux #483 DEBUG sendVeraFluxData: Payload length: 492 <0x743fa520>
50      03/17/19 16:12:46.143   luup_log:483: VeraFlux #483 ERROR: InfluxDB server replied: connection refused, expected 204 <0x743fa520>
50      03/17/19 16:12:46.143   luup_log:483: VeraFlux #483 ERROR: InfluxDB reply: } <0x

What can be wrong?
Database is created, collectd enabld and also udp enabled. Addtionally I hjave telegraf running.
Could it be a problem?

**Comment by antonywinn** [comment]
Make sure your influx instance is responding on the http IP address and port you configured in the plugin settings.

You can test from a browser: http://<influx_IP>:<influx_Port>/ping?verbose=true

eg http://192.168.0.29:8086/ping?verbose=true

Should return the version of Influx that is running.

**Comment by Mhaluch** [comment]
Hii

Thank you for answer however I found the solution.

To be honest I am a bit confused and I hope that you can correct me if I am wrong.

1. Your solution for collectd and the "veraflux" plugin are working together or are separate? 
At the beginning I thought are this same, so I have configured the plugin to use the 25826 UDP port. This is the reason why Influx was rejecting this because HTTP request are handled by different port.
After changing the plugin to HTTP port (my case 5100 because 8086 is used by different plugin) it started to work.

2. I still have the problem with collectd downloaded from repostiry which you have mentioned. For some reason, Installation was succeesfull but Vera is not sending anything towards the Influx. Netstat is not showing any connection for 25826 port. Can you plesae share working example of collectd.conf? I have started the port mirroring on the switch and nothing using UDP 25826 is send. I do not know why and cannot find any logs of collectd apllication.

**Comment by antonywinn** [comment]
VeraFlux and collectd are two completely separate things.

Veraflux uses the InfluxDB HTTP API to send data from inside Vera's Luup Engine. It doesn't interact in any way with collectd.

collectd is installed on the underlying OS and configured to send data to the collectd interface of InfluxDB directly.

 I'll dig up a copy of the collectd.conf and attach later.

**Comment by antonywinn** [comment]
Have added sample files here: https://github.com/livehouse-automation/veraflux/tree/master/collectd

Also, don't forget the InfluxDB configuration steps where you need to copy types.db so that it can understand the data being sent from collectd on Vera.
