### ISSUE TITLE
Plugin causes errors in log

### ISSUE THREAD

**Issue by RogierSchuring** [livehouse-automation/veraflux#17]
I noticed the following "errors" in the vera3 log (lines are in red, so I assume they are errors):
01	12/14/19 22:38:59.185	GetLuaInterface can't find device type: 3/0x1a6fbd8 str: 44 <0x2de71680>
01	12/14/19 22:38:59.186	luup_device_supports_service interface 0x1a6f810 args 2 <0x2de71680>

These two lines are there for every "service" in the servicesTable. By default you have 19 defined, so 38 error lines are in the log every minute.

With debug enabled:
`50	12/14/19 22:55:18.101	luup_log:486: VeraFlux #486 DEBUG STARTING SCHEDULED POLLING <0x2dcc7680>
01	12/14/19 22:55:19.164	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.164	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.165	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.166	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.166	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.167	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.167	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.168	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.169	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.169	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.170	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.170	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.171	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.172	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.173	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.173	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.174	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.174	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.175	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.176	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.176	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.177	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.177	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.178	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.179	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.179	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.180	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.180	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.181	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.182	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.183	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.183	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.184	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.184	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.185	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.186	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
01	12/14/19 22:55:19.186	GetLuaInterface can't find device type: 3/0x15f37c0 str: 44 <0x2dcc7680>
01	12/14/19 22:55:19.187	luup_device_supports_service interface 0x15f3438 args 2 <0x2dcc7680>
50	12/14/19 22:55:19.751	luup_log:486: VeraFlux #486 DEBUG sendVeraFluxData called via veraFluxOnTimer <0x2dcc7680>
50	12/14/19 22:55:19.752	luup_log:486: VeraFlux #486 DEBUG sendVeraFluxData: Payload length: 142702 <0x2dcc7680>
50	12/14/19 22:55:19.896	luup_log:486: VeraFlux #486 DEBUG InfluxDB server replied: 204 <0x2dcc7680>
50	12/14/19 22:55:19.896	luup_log:486: VeraFlux #486 DEBUG FINISHED SCHEDULED POLLING <0x2dcc7680>
50	12/14/19 22:55:19.897	luup_log:486: VeraFlux #486 Flux Capacitor Online, 1.21 Gigawatts available. <0x2dcc7680>`

Functionality  of VeraFlux does not seem to be impacted by this.

Do you have any idea what this could be?

**Comment by antonywinn** [comment]
I don't think the error is caused by the plugin, it's an inbuilt Luup function telling you that a device you have (ID: 44) doesn't properly conform to what whatever standard they have, but have never published.

As VeraFlux queries all the devices to determine what variables/properties it supports, you'll see this error multiple times based on the number of lines in the services table.

I have 2 Vera's running the plugin, on one I do not see GetLuaInterface errors, on the other, where I have a Water Tank Level plugin that I wrote myself, I do see that error for that device.

You'll see that error even when Veraflux debug logging is off, if there is a problem with the device.

**Comment by RogierSchuring** [comment]
Confirmed.
An old plugin that seemed removed (not visible in the ui) was apparently not completely removed. (View Vera Event Log).
I forced removal of the left over device and no more errors in the logs :)
Thanks!
