### ISSUE TITLE
Adding new sensor types

### ISSUE THREAD

**Issue by perhusaas** [livehouse-automation/veraflux#19]
My Aqara sensors have pressure measurement as well, and i want this over to influx. 

i tried to add this in the servicesTable{}:
`
servicesTable['urn:schemas-micasaverde-com:device:BarometerSensor1'] = {}
servicesTable['urn:schemas-micasaverde-com:device:BarometerSensor1']['fields'] = {"CurrentPressure"}
servicesTable['urn:schemas-micasaverde-com:device:BarometerSensor1']['watchedFields'] = {}
servicesTable['urn:schemas-micasaverde-com:device:BarometerSensor1']['tags'] = {}
`

This didn't generate a new entry in the "measurements" column in influxdb, what else is needed?

**Comment by antonywinn** [comment]
I don’t think we made provisions for pressure sensors as they’re not a standard z-wave class. I’ll take a look over the next couple days, shouldn’t be difficult to add.

**Comment by antonywinn** [comment]
Can you provide a copy of the device files for the sensor? the xml, json and any js/lua files as well.

**Comment by perhusaas** [comment]
Attached.

[Barosensor.zip](https://github.com/livehouse-automation/veraflux/files/5795441/Barosensor.zip)

**Comment by antonywinn** [comment]
Have you tried using upnp-org as your service schema? The device contains a mix of both, and I think the values are in the other schema.

**Comment by perhusaas** [comment]
just rename to upnp-org instead of micasaverde in the lines above? if so, i'll try that..

**Comment by antonywinn** [comment]
Assuming resolved, as not heard back from OP.
