### ISSUE TITLE
Unable to update Influx IP

### ISSUE THREAD

**Issue by Bubbgump209** [livehouse-automation/veraflux#21]
I moved my InfluxDB server and need to update the IP the plugin points to. However, when I click "Save and reload" nothing happens. I have tried this in multiple browsers. If this isn't something that can be fixed easily or can't be reproduced, is there somewhere I can manually update the IP via SSH?

**Comment by antonywinn** [comment]
You can edit the variable directly in Vera's UI.

![image](https://user-images.githubusercontent.com/31195332/106971133-3dcda580-6789-11eb-846e-b757d8a092a4.png)

**Comment by Bubbgump209** [comment]
That worked perfectly. I'm embarrassed I didn't find it myself. Thank you!
